version: '4.17'

services:
  node:
    container_name: NODEJS_SERVER
    restart: always
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    container_name: MONGODB_SERVER
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: